# Generated by Django 5.2.3 on 2025-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='summa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
