# Generated by Django 5.2.3 on 2025-06-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_auth', '0002_role_summa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='summa',
        ),
    ]
